//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Sign up for a DaaS subscription

This Quick Start requires a Citrix Cloud tenant with an active trial or a paid subscription to the Citrix DaaS service. If you don't have a subscription, https://www.citrix.com/products/citrix-cloud/form/inquiry/[contact a Citrix representative].

=== Create a Secure Client

After you obtain a DaaS subscription, refer to https://developer.cloud.com/citrix-cloud/citrix-cloud-api-overview/docs/get-started-with-citrix-cloud-apis#create-an-api-client[Create an API client] to create a secure client in your Citrix Cloud tenant.

When creating the client, you must copy the Secure Client ID, Secure Client Secret, and Customer ID provided. The Quick Start template requires these values to deploy the Quick Start. When you deploy the Quick Start, enter them in the AWS CloudFormation console for the following parameters:

* **Citrix Customer ID** – Quick Start *Citrix Cloud Customer ID* (`CitrixCustomerId`) parameter.
* **Citrix Secure Client ID** – Quick Start *Citrix Cloud Secure Client ID* (`CitrixAPIClientID`) parameter.
* **Citrix Secure Client Secret** – Quick Start *Citrix Cloud Secure Client Secret* (`CitrixAPIClientSecret`) parameter.